# -- Dataslots --
#
# $Id: Dataslots.comp 25528 2013-07-02 09:23:01Z loose $
#
#      name            vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
node   Dataslots     4.0.0  development 'node constraint'  "Placeholder for dataslot lists for each station"

#    name                    dir. type   unit   prun. vm   value                   constr.  descr.
#--------------------------------------------------------------------------------------------------------
uses  DataslotInfo    4.0.0  development '1'		       "Dataslot (beamlet) allocation"

