# -- ObsSW--
#
# $Id: ObsSW.comp 25528 2013-07-02 09:23:01Z loose $
#
#      name        vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
node  ObsSW        4.0.3  development 'node constraint'  "Observation Software"
uses  Observation  4.0.3  development 1                  "Observations under this SW control"
